version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-lab1
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./:/var/www/html:cached